export const Fr = {
    dark:"dark",
    light:"light",
    noble:"noble",
    success:"success",
    danger:"danger",
    warning:"warning",
    info:"info",
}
export enum Position {
    t='t',
    b='b',
    l='l',
    r='r',
    tl='tl',
    tc='tc',
    tr='tr',
    bl='bl',
    bc='bc',
    br='br',
    lt='lt',
    lc='lc',
    lb='lb',
    rt='rt',
    rc='rc',
    rb='rb',
}